In [39]:
import pycaret
import pandas as pd
import numpy as np

In [40]:
dataset = pd.read_csv('df3.csv')
# setup_clf = setup(data=dataset, target='Result_v1')
dataset.drop(['Unnamed: 0'], axis = 1, inplace = True)

In [41]:
dataset

,url_len,url_num_hyphens_dom,url_path_len,url_domain_len,url_num_dots,url_num_underscores,url_query_len,url_num_query_para,url_ip_present,url_entropy,...,html_num_tags('iframe'),html_num_tags('script'),html_num_tags('embed'),html_num_tags('object'),html_num_tags('div'),html_num_tags('head'),html_num_tags('body'),html_num_tags('form'),html_num_tags('a'),Result_v1
0,23.0,0.0,8.0,15.0,2.0,0.0,0.0,0.0,0.0,4.260333,...,0.0,7.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0
1,75.0,0.0,58.0,17.0,6.0,0.0,0.0,0.0,0.0,4.636107,...,0.0,18.0,0.0,0.0,20.0,1.0,1.0,0.0,21.0,1
2,20.0,0.0,4.0,16.0,2.0,0.0,0.0,0.0,0.0,3.708966,...,1.0,33.0,0.0,0.0,101.0,1.0,1.0,3.0,70.0,1
3,27.0,0.0,13.0,14.0,3.0,0.0,0.0,0.0,0.0,4.025592,...,0.0,15.0,0.0,0.0,151.0,1.0,1.0,1.0,55.0,1
4,39.0,2.0,12.0,27.0,2.0,0.0,0.0,0.0,0.0,4.631833,...,0.0,10.0,0.0,0.0,332.0,1.0,1.0,0.0,321.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3657,68.0,3.0,16.0,52.0,2.0,0.0,0.0,0.0,0.0,4.135356,...,0.0,0.0,0.0,0.0,11.0,1.0,1.0,0.0,3.0,0
3658,66.0,0.0,48.0,18.0,2.0,0.0,0.0,0.0,0.0,4.362331,...,1.0,14.0,0.0,0.0,212.0,1.0,1.0,3.0,475.0,1
3659,90.0,1.0,64.0,26.0,4.0,0.0,0.0,0.0,0.0,4.693343,...,0.0,13.0,0.0,0.0,75.0,1.0,1.0,2.0,103.0,0
3660,46.0,0.0,33.0,13.0,3.0,0.0,0.0,0.0,0.0,4.604166,...,0.0,0.0,0.0,0.0,4.0,1.0,1.0,0.0,3.0,1
3661,18.0,0.0,0.0,18.0,2.0,0.0,0.0,0.0,0.0,3.619471,...,0.0,3.0,0.0,0.0,282.0,1.0,1.0,2.0,46.0,1

In [42]:
data = dataset.sample(frac=0.8, random_state=2022) 
data_unseen = dataset.drop(data.index) 
data.reset_index(drop=True, inplace=True) 
data_unseen.reset_index(drop=True, inplace=True) 
print('Data for Modeling: ' + str(data.shape)) 
print('Data For Predictions: ' + str(data_unseen.shape))

Data for Modeling: (2930, 21)
Data For Predictions: (732, 21)

In [43]:
data.index

RangeIndex(start=0, stop=2930, step=1)

In [44]:
data

,url_len,url_num_hyphens_dom,url_path_len,url_domain_len,url_num_dots,url_num_underscores,url_query_len,url_num_query_para,url_ip_present,url_entropy,...,html_num_tags('iframe'),html_num_tags('script'),html_num_tags('embed'),html_num_tags('object'),html_num_tags('div'),html_num_tags('head'),html_num_tags('body'),html_num_tags('form'),html_num_tags('a'),Result_v1
0,14.0,0.0,1.0,13.0,1.0,0.0,0.0,0.0,0.0,3.689704,...,0.0,7.0,0.0,0.0,332.0,1.0,1.0,2.0,4.0,0
1,37.0,0.0,24.0,13.0,3.0,0.0,0.0,0.0,0.0,4.299896,...,0.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1
2,36.0,1.0,17.0,19.0,2.0,0.0,0.0,0.0,0.0,4.379298,...,0.0,2.0,0.0,0.0,41.0,1.0,1.0,1.0,18.0,0
3,17.0,0.0,0.0,17.0,2.0,0.0,0.0,0.0,0.0,3.970176,...,0.0,15.0,0.0,0.0,59.0,1.0,1.0,0.0,36.0,1
4,18.0,0.0,5.0,13.0,4.0,0.0,0.0,0.0,1.0,3.543465,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,32.0,0.0,10.0,22.0,3.0,0.0,0.0,0.0,0.0,4.214263,...,0.0,2.0,0.0,0.0,25.0,1.0,1.0,1.0,15.0,0
2926,72.0,0.0,58.0,14.0,2.0,0.0,0.0,0.0,0.0,4.787446,...,0.0,1.0,0.0,0.0,2.0,1.0,2.0,1.0,0.0,0
2927,82.0,0.0,66.0,16.0,4.0,0.0,0.0,0.0,0.0,4.510744,...,0.0,7.0,0.0,0.0,9.0,1.0,1.0,1.0,0.0,0
2928,27.0,0.0,12.0,15.0,3.0,0.0,0.0,0.0,0.0,3.976450,...,0.0,0.0,0.0,0.0,9.0,1.0,1.0,0.0,3.0,1
2929,18.0,0.0,7.0,11.0,3.0,0.0,0.0,0.0,1.0,3.973661,...,0.0,2.0,0.0,0.0,5.0,1.0,1.0,1.0,2.0,1

In [47]:
from pycaret.classification import *
import jinja2
exp_clf = setup(data = dataset, target = 'Result_v1', session_id=2022)

In [48]:
best_model = compare_models(fold = 20)

In [49]:
rf = create_model('rf')
tuned_rf = tune_model(rf)

lightgbm = create_model('lightgbm')
tuned_lightgbm = tune_model(lightgbm)

xgboost = create_model('xgboost')
tuned_xgboost = tune_model(xgboost)

In [50]:
blender = blend_models(estimator_list = [tuned_lightgbm, tuned_xgboost, tuned_rf])

In [51]:
final_model = finalize_model(blender)
prediction = predict_model(final_model, data = data_unseen)

In [53]:
final_model

VotingClassifier(estimators=[('lightgbm',
                              LGBMClassifier(bagging_fraction=0.9,
                                             bagging_freq=4,
                                             boosting_type='gbdt',
                                             class_weight=None,
                                             colsample_bytree=1.0,
                                             feature_fraction=0.8,
                                             importance_type='split',
                                             learning_rate=0.5, max_depth=-1,
                                             min_child_samples=16,
                                             min_child_weight=0.001,
                                             min_split_gain=0.1,
                                             n_estimators=120, n_jobs=-1,
                                             num_leaves=80, objective=None,
                                             ran...
                                                     max_depth=8,
                                                     max_features=1.0,
                                                     max_leaf_nodes=None,
                                                     max_samples=None,
                                                     min_impurity_decrease=0.001,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=5,
                                                     min_samples_split=7,
                                                     min_weight_fraction_leaf=0.0,
                                                     n_estimators=40, n_jobs=-1,
                                                     oob_score=False,
                                                     random_state=2022,
                                                     verbose=0,
                                                     warm_start=False))],
                 flatten_transform=True, n_jobs=-1, verbose=False,
                 voting='soft', weights=None)

In [54]:
best_model_3 = compare_models(n_select=3)
blender_3 = blend_models(best_model_3)

In [56]:
final_model1 = finalize_model(blender_3)
prediction1 = predict_model(final_model1, data = data_unseen)

In [59]:
final_model1

VotingClassifier(estimators=[('lightgbm',
                              LGBMClassifier(boosting_type='gbdt',
                                             class_weight=None,
                                             colsample_bytree=1.0,
                                             importance_type='split',
                                             learning_rate=0.1, max_depth=-1,
                                             min_child_samples=20,
                                             min_child_weight=0.001,
                                             min_split_gain=0.0,
                                             n_estimators=100, n_jobs=-1,
                                             num_leaves=31, objective=None,
                                             random_state=2022, reg_alpha=0.0,
                                             reg_lambda=0.0, silent='warn'...
                                            learning_rate=0.300000012,
                                            max_bin=256, max_cat_to_onehot=4,
                                            max_delta_step=0, max_depth=6,
                                            max_leaves=0, min_child_weight=1,
                                            missing=nan,
                                            monotone_constraints='()',
                                            n_estimators=100, n_jobs=-1,
                                            num_parallel_tree=1,
                                            objective='binary:logistic',
                                            predictor='auto', random_state=2022,
                                            reg_alpha=0, ...))],
                 flatten_transform=True, n_jobs=-1, verbose=False,
                 voting='soft', weights=None)